// Generated by scripts/generate-types.ts from svelte 5.57.1's types (MIT). Do not edit.
import type {
  ArrayExpression,
  ArrowFunctionExpression,
  ChainExpression,
  Expression,
  Identifier,
  MemberExpression,
  Node,
  ObjectExpression,
  Pattern,
  Program,
  SequenceExpression,
  SimpleCallExpression,
  SourceLocation,
  VariableDeclaration,
  VariableDeclarator,
} from "./estree";

type Namespace = "html" | "svg" | "mathml";

export declare namespace AST {
  export interface BaseNode {
    type: string;
    start: number;
    end: number;
  }

  export interface Fragment {
    type: "Fragment";
    nodes: Array<Text | Tag | ElementLike | Block | Comment>;
  }

  export interface Root extends BaseNode {
    type: "Root";
    /**
     * Inline options provided by `<svelte:options>` — these override options passed to `compile(...)`
     */
    options: SvelteOptions | null;
    fragment: Fragment;
    /** The parsed `<style>` element, if exists */
    css: AST.CSS.StyleSheet | null;
    /** The parsed `<script>` element, if exists */
    instance?: Script | null;
    /** The parsed `<script module>` element, if exists */
    module?: Script | null;
    /** Comments found in <script> and {expressions} */
    comments: JSComment[];
  }

  export interface SvelteOptions {
    // start/end info (needed for warnings and for our Prettier plugin)
    start: number;
    end: number;
    // options
    runes?: boolean;
    immutable?: boolean;
    accessors?: boolean;
    preserveWhitespace?: boolean;
    namespace?: Namespace;
    css?: "injected";
    customElement?: {
      tag?: string;
      shadow?: "open" | "none" | ObjectExpression | undefined;
      props?: Record<
        string,
        {
          attribute?: string;
          reflect?: boolean;
          type?: "Array" | "Boolean" | "Number" | "Object" | "String";
        }
      >;
      /**
       * Is of type
       * ```ts
       * (ceClass: new () => HTMLElement) => new () => HTMLElement
       * ```
       */
      extend?: ArrowFunctionExpression | Identifier;
    };
    attributes: Attribute[];
  }

  /** Static text */
  export interface Text extends BaseNode {
    type: "Text";
    /** Text with decoded HTML entities */
    data: string;
    /** The original text, with undecoded HTML entities */
    raw: string;
  }

  /** A (possibly reactive) template expression — `{...}` */
  export interface ExpressionTag extends BaseNode {
    type: "ExpressionTag";
    expression: Expression;
  }

  /** A (possibly reactive) HTML template expression — `{@html ...}` */
  export interface HtmlTag extends BaseNode {
    type: "HtmlTag";
    expression: Expression;
  }

  /** An HTML comment */
  // TODO rename to disambiguate
  export interface Comment extends BaseNode {
    type: "Comment";
    /** the contents of the comment */
    data: string;
  }

  /** A `{@const ...}` tag */
  export interface ConstTag extends BaseNode {
    type: "ConstTag";
    declaration: VariableDeclaration & {
      declarations: [VariableDeclarator & { id: Pattern; init: Expression }];
    };
  }

  /** A `{let ...}` or `{const ...}` tag */
  export interface DeclarationTag extends BaseNode {
    type: "DeclarationTag";
    declaration: VariableDeclaration;
  }

  /** A `{@debug ...}` tag */
  export interface DebugTag extends BaseNode {
    type: "DebugTag";
    identifiers: Identifier[];
  }

  /** A `{@render foo(...)} tag */
  export interface RenderTag extends BaseNode {
    type: "RenderTag";
    expression:
      | SimpleCallExpression
      | (ChainExpression & { expression: SimpleCallExpression });
  }

  /** A `{@attach foo(...)} tag */
  export interface AttachTag extends BaseNode {
    type: "AttachTag";
    expression: Expression;
  }

  /** An `animate:` directive */
  export interface AnimateDirective extends BaseAttribute {
    type: "AnimateDirective";
    /** The 'x' in `animate:x` */
    name: string;
    /** The y in `animate:x={y}` */
    expression: null | Expression;
  }

  /** A `bind:` directive */
  export interface BindDirective extends BaseAttribute {
    type: "BindDirective";
    /** The 'x' in `bind:x` */
    name: string;
    /** The y in `bind:x={y}` */
    expression: Identifier | MemberExpression | SequenceExpression;
  }

  /** A `class:` directive */
  export interface ClassDirective extends BaseAttribute {
    type: "ClassDirective";
    /** The 'x' in `class:x` */
    name: "class";
    /** The 'y' in `class:x={y}`, or the `x` in `class:x` */
    expression: Expression;
  }

  /** A `let:` directive */
  export interface LetDirective extends BaseAttribute {
    type: "LetDirective";
    /** The 'x' in `let:x` */
    name: string;
    /** The 'y' in `let:x={y}` */
    expression: null | Identifier | ArrayExpression | ObjectExpression;
  }

  /** An `on:` directive */
  export interface OnDirective extends BaseAttribute {
    type: "OnDirective";
    /** The 'x' in `on:x` */
    name: string;
    /** The 'y' in `on:x={y}` */
    expression: null | Expression;
    modifiers: Array<
      | "capture"
      | "nonpassive"
      | "once"
      | "passive"
      | "preventDefault"
      | "self"
      | "stopImmediatePropagation"
      | "stopPropagation"
      | "trusted"
    >;
  }

  /** A `style:` directive */
  export interface StyleDirective extends BaseAttribute {
    type: "StyleDirective";
    /** The 'x' in `style:x` */
    name: string;
    /** The 'y' in `style:x={y}` */
    value: true | ExpressionTag | Array<ExpressionTag | Text>;
    modifiers: Array<"important">;
  }

  // TODO have separate in/out/transition directives
  /** A `transition:`, `in:` or `out:` directive */
  export interface TransitionDirective extends BaseAttribute {
    type: "TransitionDirective";
    /** The 'x' in `transition:x` */
    name: string;
    /** The 'y' in `transition:x={y}` */
    expression: null | Expression;
    modifiers: Array<"local" | "global">;
    /** True if this is a `transition:` or `in:` directive */
    intro: boolean;
    /** True if this is a `transition:` or `out:` directive */
    outro: boolean;
  }

  /** A `use:` directive */
  export interface UseDirective extends BaseAttribute {
    type: "UseDirective";
    /** The 'x' in `use:x` */
    name: string;
    /** The 'y' in `use:x={y}` */
    expression: null | Expression;
  }

  export interface BaseElement extends BaseNode {
    name: string;
    /** Only with `parse(source, { loc: true })`. */
    name_loc?: SourceLocation;
    attributes: Array<Attribute | SpreadAttribute | Directive | AttachTag>;
    fragment: Fragment;
  }

  export interface Component extends BaseElement {
    type: "Component";
  }

  export interface TitleElement extends BaseElement {
    type: "TitleElement";
    name: "title";
  }

  export interface SlotElement extends BaseElement {
    type: "SlotElement";
    name: "slot";
  }

  export interface RegularElement extends BaseElement {
    type: "RegularElement";
  }

  export interface SvelteBody extends BaseElement {
    type: "SvelteBody";
    name: "svelte:body";
  }

  export interface SvelteComponent extends BaseElement {
    type: "SvelteComponent";
    name: "svelte:component";
    expression: Expression;
  }

  export interface SvelteDocument extends BaseElement {
    type: "SvelteDocument";
    name: "svelte:document";
  }

  export interface SvelteElement extends BaseElement {
    type: "SvelteElement";
    name: "svelte:element";
    tag: Expression;
  }

  export interface SvelteFragment extends BaseElement {
    type: "SvelteFragment";
    name: "svelte:fragment";
  }

  export interface SvelteBoundary extends BaseElement {
    type: "SvelteBoundary";
    name: "svelte:boundary";
  }

  export interface SvelteHead extends BaseElement {
    type: "SvelteHead";
    name: "svelte:head";
  }

  /** This is only an intermediate representation while parsing, it doesn't exist in the final AST */
  export interface SvelteOptionsRaw extends BaseElement {
    type: "SvelteOptions";
    name: "svelte:options";
  }

  export interface SvelteSelf extends BaseElement {
    type: "SvelteSelf";
    name: "svelte:self";
  }

  export interface SvelteWindow extends BaseElement {
    type: "SvelteWindow";
    name: "svelte:window";
  }

  /** An `{#each ...}` block */
  export interface EachBlock extends BaseNode {
    type: "EachBlock";
    expression: Expression;
    /** The `entry` in `{#each item as entry}`. `null` if `as` part is omitted */
    context: Pattern | null;
    body: Fragment;
    fallback?: Fragment;
    index?: string;
    key?: Expression;
  }

  /** An `{#if ...}` block */
  export interface IfBlock extends BaseNode {
    type: "IfBlock";
    elseif: boolean;
    test: Expression;
    consequent: Fragment;
    alternate: Fragment | null;
  }

  /** An `{#await ...}` block */
  export interface AwaitBlock extends BaseNode {
    type: "AwaitBlock";
    expression: Expression;
    // TODO can/should we move these inside the ThenBlock and CatchBlock?
    /** The resolved value inside the `then` block */
    value: Pattern | null;
    /** The rejection reason inside the `catch` block */
    error: Pattern | null;
    pending: Fragment | null;
    then: Fragment | null;
    catch: Fragment | null;
  }

  export interface KeyBlock extends BaseNode {
    type: "KeyBlock";
    expression: Expression;
    fragment: Fragment;
  }

  export interface SnippetBlock extends BaseNode {
    type: "SnippetBlock";
    expression: Identifier;
    parameters: Pattern[];
    typeParams?: string;
    body: Fragment;
  }

  export interface BaseAttribute extends BaseNode {
    name: string;
    /** Only with `parse(source, { loc: true })`. */
    name_loc?: SourceLocation | null;
  }

  export interface Attribute extends BaseAttribute {
    type: "Attribute";
    /**
     * Quoted/string values are represented by an array, even if they contain a single expression like `"{x}"`
     */
    value: true | ExpressionTag | Array<Text | ExpressionTag>;
  }

  export interface SpreadAttribute extends BaseNode {
    type: "SpreadAttribute";
    expression: Expression;
  }

  export interface Script extends BaseNode {
    type: "Script";
    context: "default" | "module";
    content: Program;
    attributes: Attribute[];
  }

  export interface JSComment {
    type: "Line" | "Block";
    value: string;
    start: number;
    end: number;
    /** Only with `parse(source, { loc: true })`. */
    loc?: {
      start: { line: number; column: number };
      end: { line: number; column: number };
    };
  }

  export type AttributeLike = Attribute | SpreadAttribute | Directive;

  export type Directive =
    | AST.AnimateDirective
    | AST.BindDirective
    | AST.ClassDirective
    | AST.LetDirective
    | AST.OnDirective
    | AST.StyleDirective
    | AST.TransitionDirective
    | AST.UseDirective;

  export type Block =
    | AST.EachBlock
    | AST.IfBlock
    | AST.AwaitBlock
    | AST.KeyBlock
    | AST.SnippetBlock;

  export type ElementLike =
    | AST.Component
    | AST.TitleElement
    | AST.SlotElement
    | AST.RegularElement
    | AST.SvelteBody
    | AST.SvelteBoundary
    | AST.SvelteComponent
    | AST.SvelteDocument
    | AST.SvelteElement
    | AST.SvelteFragment
    | AST.SvelteHead
    | AST.SvelteOptionsRaw
    | AST.SvelteSelf
    | AST.SvelteWindow
    | AST.SvelteBoundary;

  export type Tag =
    | AST.AttachTag
    | AST.ConstTag
    | AST.DeclarationTag
    | AST.DebugTag
    | AST.ExpressionTag
    | AST.HtmlTag
    | AST.RenderTag;

  export type TemplateNode =
    | AST.Root
    | AST.Text
    | Tag
    | ElementLike
    | AST.Attribute
    | AST.SpreadAttribute
    | Directive
    | AST.AttachTag
    | AST.Comment
    | Block;

  export type SvelteNode =
    | Node
    | TemplateNode
    | AST.Fragment
    | _CSS.Node
    | Script;

  export type { _CSS as CSS };
}

declare namespace _CSS {
  export interface BaseNode {
    start: number;
    end: number;
  }

  export interface StyleSheetBase extends BaseNode {
    children: Array<Atrule | Rule>;
    /** CSS comments in source order */
    comments: CSSComment[];
  }

  export interface CSSComment extends BaseNode {
    type: "CSSComment";
    value: string;
    /** Character offset in a containing declaration value or at-rule prelude */
    position?: number;
  }

  export interface StyleSheetFile extends StyleSheetBase {
    type: "StyleSheetFile";
  }

  export interface StyleSheet extends StyleSheetBase {
    type: "StyleSheet";
    attributes: any[]; // TODO
    content: {
      start: number;
      end: number;
      styles: string;
      /** Possible comment atop the style tag */
      comment: AST.Comment | null;
    };
  }

  export interface Atrule extends BaseNode {
    type: "Atrule";
    name: string;
    prelude: string;
    block: Block | null;
  }

  export interface Rule extends BaseNode {
    type: "Rule";
    prelude: SelectorList;
    block: Block;
  }

  /**
   * A list of selectors, e.g. `a, b, c {}`
   */
  export interface SelectorList extends BaseNode {
    type: "SelectorList";
    /**
     * The `a`, `b` and `c` in `a, b, c {}`
     */
    children: ComplexSelector[];
  }

  /**
   * A complex selector, e.g. `a b c {}`
   */
  export interface ComplexSelector extends BaseNode {
    type: "ComplexSelector";
    /**
     * The `a`, `b` and `c` in `a b c {}`
     */
    children: RelativeSelector[];
  }

  /**
   * A relative selector, e.g the `a` and `> b` in `a > b {}`
   */
  export interface RelativeSelector extends BaseNode {
    type: "RelativeSelector";
    /**
     * In `a > b`, `> b` forms one relative selector, and `>` is the combinator. `null` for the first selector.
     */
    combinator: null | Combinator;
    /**
     * The `b:is(...)` in `> b:is(...)`
     */
    selectors: SimpleSelector[];
  }

  export interface TypeSelector extends BaseNode {
    type: "TypeSelector";
    name: string;
    namespace?: string;
  }

  export interface IdSelector extends BaseNode {
    type: "IdSelector";
    name: string;
  }

  export interface ClassSelector extends BaseNode {
    type: "ClassSelector";
    name: string;
  }

  export interface AttributeSelector extends BaseNode {
    type: "AttributeSelector";
    name: string;
    matcher: string | null;
    value: string | null;
    flags: string | null;
  }

  export interface PseudoElementSelector extends BaseNode {
    type: "PseudoElementSelector";
    name: string;
    args?: SelectorList;
  }

  export interface PseudoClassSelector extends BaseNode {
    type: "PseudoClassSelector";
    name: string;
    args: SelectorList | null;
  }

  export interface Percentage extends BaseNode {
    type: "Percentage";
    value: string;
  }

  export interface NestingSelector extends BaseNode {
    type: "NestingSelector";
    name: "&";
  }

  export interface Nth extends BaseNode {
    type: "Nth";
    value: string;
  }

  export type SimpleSelector =
    | TypeSelector
    | IdSelector
    | ClassSelector
    | AttributeSelector
    | PseudoElementSelector
    | PseudoClassSelector
    | Percentage
    | Nth
    | NestingSelector;

  export interface Combinator extends BaseNode {
    type: "Combinator";
    name: string;
  }

  export interface Block extends BaseNode {
    type: "Block";
    children: Array<Declaration | Rule | Atrule>;
  }

  export interface Declaration extends BaseNode {
    type: "Declaration";
    property: string;
    value: string;
  }

  // for zimmerframe
  export type Node =
    | StyleSheet
    | Rule
    | Atrule
    | SelectorList
    | Block
    | ComplexSelector
    | RelativeSelector
    | Combinator
    | SimpleSelector
    | Declaration;
}
