import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { $ } from "bun";

const root = join(import.meta.dir, "..");
const read = (path: string) => readFileSync(join(root, path), "utf8");
const version = (name: string) =>
  JSON.parse(read(`node_modules/${name}/package.json`)).version;

const LOC_ONLY = "/** Only with `parse(source, { loc: true })`. */";

function block(source: string, header: string): string {
  const start = source.indexOf(header);
  if (start === -1) throw new Error(`not found: ${header}`);
  let depth = 0;
  for (let i = source.indexOf("{", start); i < source.length; i++) {
    if (source[i] === "{") depth++;
    else if (source[i] === "}" && --depth === 0) {
      return source.slice(start, i + 1);
    }
  }
  throw new Error(`unbalanced: ${header}`);
}

function replaceOnce(text: string, from: string, to: string): string {
  if (!text.includes(from)) throw new Error(`not found: ${from}`);
  return text.replaceAll(from, to);
}

const estree = read("node_modules/@types/estree/index.d.ts");
writeFileSync(
  join(root, "src/types/estree.ts"),
  `// Generated by scripts/generate-types.ts from @types/estree ${version("@types/estree")} (MIT, Copyright (c) Microsoft Corporation). Do not edit.\n\n${estree}`,
);

const types = read("node_modules/svelte/types/index.d.ts");
const compiler = block(types, "declare module 'svelte/compiler' {");
const estreeImport = compiler.match(/import type \{([^}]+)\} from 'estree';/);
if (!estreeImport) throw new Error("estree import not found");

let ast = block(compiler, "\texport namespace AST {");
ast = replaceOnce(
  ast,
  "\t\t\tname_loc: SourceLocation;",
  `\t\t\t${LOC_ONLY}\n\t\t\tname_loc?: SourceLocation;`,
);
ast = replaceOnce(
  ast,
  "\t\t\tname_loc: SourceLocation | null;",
  `\t\t\t${LOC_ONLY}\n\t\t\tname_loc?: SourceLocation | null;`,
);
ast = replaceOnce(
  ast,
  "\t\t\tvalue: string;\n\t\t\tstart: number;\n\t\t\tend: number;\n\t\t\tloc: {",
  `\t\t\tvalue: string;\n\t\t\tstart: number;\n\t\t\tend: number;\n\t\t\t${LOC_ONLY}\n\t\t\tloc?: {`,
);
ast = replaceOnce(
  ast,
  "\t\t\tinstance: Script | null;",
  "\t\t\tinstance?: Script | null;",
);
ast = replaceOnce(
  ast,
  "\t\t\tmodule: Script | null;",
  "\t\t\tmodule?: Script | null;",
);
const css = block(compiler, "\tnamespace _CSS {");
const namespace = compiler.match(/\ttype Namespace = [^;]+;/)?.[0];
if (!namespace) throw new Error("Namespace type not found");

const dedent = (text: string) => text.replace(/^\t/gm, "");
const out = join(root, "src/types/svelte-ast.ts");
writeFileSync(
  out,
  `// Generated by scripts/generate-types.ts from svelte ${version("svelte")}'s types (MIT). Do not edit.
import type {${estreeImport[1]}} from "./estree";

${dedent(namespace)}

${dedent(ast).replace(/^export namespace AST/, "export declare namespace AST")}

${dedent(css).replace(/^namespace _CSS/, "declare namespace _CSS")}
`,
);

await $`bunx biome format --write ${join(root, "src/types")}`.quiet();
console.log("✓ src/types/estree.ts and src/types/svelte-ast.ts written");
