import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { byCodeUnit } from "./shared";

const SOURCE = "https://html.spec.whatwg.org/entities.json";

const entities: Record<string, { codepoints: number[] }> = await (
  await fetch(SOURCE)
).json();

const codes = new Map<string, number>();
for (const [name, { codepoints }] of Object.entries(entities)) {
  codes.set(name.slice(1), codepoints[0]);
}

const names = [...codes.keys()]
  .filter((name) => name.endsWith(";"))
  .map((name) => name.slice(0, -1))
  .sort(byCodeUnit);
for (const name of codes.keys()) {
  if (!name.endsWith(";") && codes.get(`${name};`) !== codes.get(name)) {
    throw new Error(`&${name} has no &${name}; with the same code point`);
  }
}

let previous = "";
const entries = names.map((name) => {
  let shared = 0;
  while (shared < previous.length && name[shared] === previous[shared]) {
    shared++;
  }
  if (shared >= 36) throw new Error(`&${name}; shares too long a prefix`);
  previous = name;
  const separator = codes.has(name) ? "!" : ":";
  const code = codes.get(`${name};`);
  if (code === undefined) throw new Error(`&${name}; has no code point`);
  return `${shared.toString(36)}${name.slice(shared)}${separator}${code.toString(36)}`;
});

writeFileSync(
  join(import.meta.dir, "../src/entities.ts"),
  `// Generated by scripts/generate-entities.ts from ${SOURCE}. Do not edit.
export const ENTITIES =\n  ${JSON.stringify(entries.join(" "))};\n`,
);
console.log(`✓ ${codes.size} entities written to src/entities.ts`);
