import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { $ } from "bun";

const CODES = [
  "attribute_duplicate",
  "attribute_empty_shorthand",
  "block_duplicate_clause",
  "block_invalid_continuation_placement",
  "block_invalid_elseif",
  "block_invalid_placement",
  "block_unclosed",
  "block_unexpected_close",
  "const_tag_invalid_expression",
  "css_empty_declaration",
  "css_expected_identifier",
  "css_selector_invalid",
  "debug_tag_invalid_arguments",
  "declaration_tag_invalid_type",
  "directive_invalid_value",
  "directive_missing_name",
  "element_invalid_closing_tag",
  "element_invalid_closing_tag_autoclosed",
  "element_unclosed",
  "expected_attribute_value",
  "expected_block_type",
  "expected_identifier",
  "expected_pattern",
  "expected_tag",
  "expected_token",
  "expected_whitespace",
  "js_parse_error",
  "render_tag_invalid_expression",
  "script_duplicate",
  "script_invalid_attribute_value",
  "script_invalid_context",
  "script_reserved_attribute",
  "style_duplicate",
  "svelte_component_invalid_this",
  "svelte_component_missing_this",
  "svelte_element_missing_this",
  "svelte_meta_duplicate",
  "svelte_meta_invalid_content",
  "svelte_meta_invalid_placement",
  "svelte_meta_invalid_tag",
  "svelte_options_deprecated_tag",
  "svelte_options_invalid_attribute",
  "svelte_options_invalid_attribute_value",
  "svelte_options_invalid_customelement",
  "svelte_options_invalid_customelement_props",
  "svelte_options_invalid_customelement_shadow",
  "svelte_options_invalid_tagname",
  "svelte_options_reserved_tagname",
  "svelte_options_unknown_attribute",
  "tag_invalid_name",
  "tag_invalid_placement",
  "unexpected_eof",
  "unexpected_reserved_word",
  "unterminated_string_constant",
  "void_element_invalid_content",
];

const root = join(import.meta.dir, "..");
const source = readFileSync(
  join(root, "node_modules/svelte/src/compiler/errors.js"),
  "utf8",
);
const version = JSON.parse(
  readFileSync(join(root, "node_modules/svelte/package.json"), "utf8"),
).version;

const FUNCTION =
  /export function (\w+)\(node(?:, ([\w, ]+))?\) \{\n\te\(node, '(\w+)', (`(?:[^`\\]|\\.)*`)\);\n\}/g;

const found = new Map<string, string>();
for (const [, name, params = "", code, message] of source.matchAll(FUNCTION)) {
  if (name !== code || !CODES.includes(code)) continue;
  const args = params
    .split(", ")
    .filter(Boolean)
    .map((param) => `${param}: string`);
  const literal = message.includes("${")
    ? message
    : JSON.stringify(Function(`return ${message}`)());
  found.set(
    code,
    `export function ${code}(${["node: NodeLike", ...args].join(", ")}): never {\n  throw new ParseError(node, "${code}", ${literal});\n}`,
  );
}

const missing = CODES.filter((code) => !found.has(code));
if (missing.length > 0) {
  throw new Error(`not found in svelte's errors.js: ${missing.join(", ")}`);
}

const out = join(root, "src/errors.ts");
writeFileSync(
  out,
  `// Generated by scripts/generate-errors.ts from svelte ${version}'s errors.js. Do not edit.\nimport { type NodeLike, ParseError } from "./parse-error";\n\n${CODES.map((code) => found.get(code)).join("\n\n")}\n`,
);
await $`bunx biome format --write ${out}`.quiet();
console.log(`✓ ${CODES.length} errors written to src/errors.ts`);
