import { writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = "https://html.spec.whatwg.org/entities.json";

const entities: Record<string, { codepoints: number[] }> = await (
  await fetch(SOURCE)
).json();

const entries = Object.entries(entities)
  .map(
    ([name, { codepoints }]) =>
      `${name.slice(1)}:${codepoints[0].toString(36)}`,
  )
  .sort();

writeFileSync(
  join(import.meta.dir, "../src/entities.ts"),
  `// Generated by scripts/generate-entities.ts from ${SOURCE}. Do not edit.\nexport const ENTITIES =\n  ${JSON.stringify(entries.join(" "))};\n`,
);
console.log(`✓ ${entries.length} entities written to src/entities.ts`);
