import type { BunPlugin } from "bun";

const ACORN_REGEXP_START =
  '// This file was generated by "bin/generate-unicode-script-values.js". Do not modify manually!';
const ACORN_REGEXP_END = "// Object type used to represent tokens.";
const ACORN_REGEXP_STUB = `var RegExpValidationState = function RegExpValidationState() {};
RegExpValidationState.prototype.reset = function () {};
Parser.prototype.validateRegExpFlags = function () {};
Parser.prototype.validateRegExpPattern = function () {};
`;

const ACORN_IDENTIFIER_TABLES =
  /^var (?:astralIdentifierCodes|astralIdentifierStartCodes|nonASCIIidentifierChars|nonASCIIidentifierStartChars) = .*;$/gm;
const ACORN_IDENTIFIER_START = "var nonASCIIidentifierStart = new RegExp(";
const ACORN_IDENTIFIER_END = "// ## Token types";
const ACORN_IDENTIFIER_STUB = `var nonASCIIidentifierStart = /\\p{ID_Start}/u;
var nonASCIIidentifier = /[\\p{ID_Continue}\\u200c\\u200d]/u;

function isIdentifierStart(code, astral) {
  if (code < 65) { return code === 36 }
  if (code < 91) { return true }
  if (code < 97) { return code === 95 }
  if (code < 123) { return true }
  if (code > 0xffff && astral === false) { return false }
  return code >= 0xaa && nonASCIIidentifierStart.test(String.fromCodePoint(code))
}

function isIdentifierChar(code, astral) {
  if (code < 48) { return code === 36 }
  if (code < 58) { return true }
  if (code < 65) { return false }
  if (code < 91) { return true }
  if (code < 97) { return code === 95 }
  if (code < 123) { return true }
  if (code > 0xffff && astral === false) { return false }
  return code >= 0xaa && nonASCIIidentifier.test(String.fromCodePoint(code))
}

`;

const TS_MEMBER = /\bts[A-Z]\w*\b/g;
const TS_PLUGIN_EXPORT = "tsPlugin";
const SHORTENED_NAME = /\$\d/;
const ACORN_FILE = /[\\/]acorn[\\/]dist[\\/]acorn\.mjs$/;
const TS_PLUGIN_FILE = /[\\/]src[\\/]ts-plugin\.ts$/;

function stripAcornRegExpValidation(source: string): string {
  const start = source.indexOf(ACORN_REGEXP_START);
  const end = source.indexOf(ACORN_REGEXP_END);
  if (start === -1 || end < start) {
    throw new Error(
      "shrink-parser: acorn's regex validator section moved; update the markers in scripts/shrink-parser.ts",
    );
  }
  return source.slice(0, start) + ACORN_REGEXP_STUB + source.slice(end);
}

function replaceAcornIdentifierTables(source: string): string {
  const tables = source.match(ACORN_IDENTIFIER_TABLES) ?? [];
  const start = source.indexOf(ACORN_IDENTIFIER_START);
  const end = source.indexOf(ACORN_IDENTIFIER_END, start);
  if (tables.length !== 4 || start === -1 || end === -1) {
    throw new Error(
      "shrink-parser: acorn's identifier tables moved; update the markers in scripts/shrink-parser.ts",
    );
  }
  const rest =
    source.slice(0, start) + ACORN_IDENTIFIER_STUB + source.slice(end);
  const stripped = rest.replace(ACORN_IDENTIFIER_TABLES, "");
  for (const name of [
    "isInAstralSet",
    "astralIdentifier",
    "nonASCIIidentifierChars",
    "nonASCIIidentifierStartChars",
  ]) {
    if (stripped.includes(name)) {
      throw new Error(
        `shrink-parser: acorn uses ${name} outside its identifier tests; update scripts/shrink-parser.ts`,
      );
    }
  }
  return stripped;
}

function shortenTsMembers(source: string): string {
  if (SHORTENED_NAME.test(source)) {
    throw new Error(
      "shrink-parser: ts-plugin.ts now uses `$<digit>` names, which collide with the shortened ones",
    );
  }
  const counts = new Map<string, number>();
  for (const [name] of source.matchAll(TS_MEMBER)) {
    if (name !== TS_PLUGIN_EXPORT)
      counts.set(name, (counts.get(name) ?? 0) + 1);
  }
  if (counts.size === 0)
    throw new Error("shrink-parser: found no `ts*` members in ts-plugin.ts");
  const names = new Map(
    [...counts]
      .sort((a, b) => b[1] - a[1])
      .map(([name], i) => [name, `$${i.toString(36)}`]),
  );
  return source.replace(TS_MEMBER, (name) => names.get(name) ?? name);
}

export const shrinkParser: BunPlugin = {
  name: "sveast-shrink-parser",
  setup(build) {
    build.onLoad({ filter: ACORN_FILE }, async (args) => ({
      contents: replaceAcornIdentifierTables(
        stripAcornRegExpValidation(await Bun.file(args.path).text()),
      ),
      loader: "js",
    }));
    build.onLoad({ filter: TS_PLUGIN_FILE }, async (args) => ({
      contents: shortenTsMembers(await Bun.file(args.path).text()),
      loader: "ts",
    }));
  },
};
