// Generated by scripts/generate-errors.ts from svelte 5.57.1's errors.js. Do not edit.
import { type NodeLike, ParseError } from "./parse-error";

export function attribute_duplicate(node: NodeLike): never {
  throw new ParseError(
    node,
    "attribute_duplicate",
    "Attributes need to be unique",
  );
}

export function attribute_empty_shorthand(node: NodeLike): never {
  throw new ParseError(
    node,
    "attribute_empty_shorthand",
    "Attribute shorthand cannot be empty",
  );
}

export function block_duplicate_clause(node: NodeLike, name: string): never {
  throw new ParseError(
    node,
    "block_duplicate_clause",
    `${name} cannot appear more than once within a block`,
  );
}

export function block_invalid_continuation_placement(node: NodeLike): never {
  throw new ParseError(
    node,
    "block_invalid_continuation_placement",
    "{:...} block is invalid at this position (did you forget to close the preceding element or block?)",
  );
}

export function block_invalid_elseif(node: NodeLike): never {
  throw new ParseError(
    node,
    "block_invalid_elseif",
    "'elseif' should be 'else if'",
  );
}

export function block_invalid_placement(
  node: NodeLike,
  name: string,
  location: string,
): never {
  throw new ParseError(
    node,
    "block_invalid_placement",
    `{#${name} ...} block cannot be ${location}`,
  );
}

export function block_unclosed(node: NodeLike): never {
  throw new ParseError(node, "block_unclosed", "Block was left open");
}

export function block_unexpected_close(node: NodeLike): never {
  throw new ParseError(
    node,
    "block_unexpected_close",
    "Unexpected block closing tag",
  );
}

export function const_tag_invalid_expression(node: NodeLike): never {
  throw new ParseError(
    node,
    "const_tag_invalid_expression",
    "{@const ...} must consist of a single variable declaration",
  );
}

export function css_empty_declaration(node: NodeLike): never {
  throw new ParseError(
    node,
    "css_empty_declaration",
    "Declaration cannot be empty",
  );
}

export function css_expected_identifier(node: NodeLike): never {
  throw new ParseError(
    node,
    "css_expected_identifier",
    "Expected a valid CSS identifier",
  );
}

export function css_selector_invalid(node: NodeLike): never {
  throw new ParseError(node, "css_selector_invalid", "Invalid selector");
}

export function debug_tag_invalid_arguments(node: NodeLike): never {
  throw new ParseError(
    node,
    "debug_tag_invalid_arguments",
    "{@debug ...} arguments must be identifiers, not arbitrary expressions",
  );
}

export function declaration_tag_invalid_type(node: NodeLike): never {
  throw new ParseError(
    node,
    "declaration_tag_invalid_type",
    "Declaration tags must be `let` or `const` declarations",
  );
}

export function directive_invalid_value(node: NodeLike): never {
  throw new ParseError(
    node,
    "directive_invalid_value",
    "Directive value must be a JavaScript expression enclosed in curly braces",
  );
}

export function directive_missing_name(node: NodeLike, type: string): never {
  throw new ParseError(
    node,
    "directive_missing_name",
    `\`${type}\` name cannot be empty`,
  );
}

export function element_invalid_closing_tag(
  node: NodeLike,
  name: string,
): never {
  throw new ParseError(
    node,
    "element_invalid_closing_tag",
    `\`</${name}>\` attempted to close an element that was not open`,
  );
}

export function element_invalid_closing_tag_autoclosed(
  node: NodeLike,
  name: string,
  reason: string,
): never {
  throw new ParseError(
    node,
    "element_invalid_closing_tag_autoclosed",
    `\`</${name}>\` attempted to close element that was already automatically closed by \`<${reason}>\` (cannot nest \`<${reason}>\` inside \`<${name}>\`)`,
  );
}

export function element_unclosed(node: NodeLike, name: string): never {
  throw new ParseError(node, "element_unclosed", `\`<${name}>\` was left open`);
}

export function expected_attribute_value(node: NodeLike): never {
  throw new ParseError(
    node,
    "expected_attribute_value",
    "Expected attribute value",
  );
}

export function expected_block_type(node: NodeLike): never {
  throw new ParseError(
    node,
    "expected_block_type",
    "Expected 'if', 'each', 'await', 'key' or 'snippet'",
  );
}

export function expected_identifier(node: NodeLike): never {
  throw new ParseError(node, "expected_identifier", "Expected an identifier");
}

export function expected_pattern(node: NodeLike): never {
  throw new ParseError(
    node,
    "expected_pattern",
    "Expected identifier or destructure pattern",
  );
}

export function expected_tag(node: NodeLike): never {
  throw new ParseError(
    node,
    "expected_tag",
    "Expected 'html', 'render', 'attach', 'const', or 'debug'",
  );
}

export function expected_token(node: NodeLike, token: string): never {
  throw new ParseError(node, "expected_token", `Expected token ${token}`);
}

export function expected_whitespace(node: NodeLike): never {
  throw new ParseError(node, "expected_whitespace", "Expected whitespace");
}

export function js_parse_error(node: NodeLike, message: string): never {
  throw new ParseError(node, "js_parse_error", `${message}`);
}

export function render_tag_invalid_expression(node: NodeLike): never {
  throw new ParseError(
    node,
    "render_tag_invalid_expression",
    "`{@render ...}` tags can only contain call expressions",
  );
}

export function script_duplicate(node: NodeLike): never {
  throw new ParseError(
    node,
    "script_duplicate",
    "A component can have a single top-level `<script>` element and/or a single top-level `<script module>` element",
  );
}

export function script_invalid_attribute_value(
  node: NodeLike,
  name: string,
): never {
  throw new ParseError(
    node,
    "script_invalid_attribute_value",
    `If the \`${name}\` attribute is supplied, it must be a boolean attribute`,
  );
}

export function script_invalid_context(node: NodeLike): never {
  throw new ParseError(
    node,
    "script_invalid_context",
    'If the context attribute is supplied, its value must be "module"',
  );
}

export function script_reserved_attribute(node: NodeLike, name: string): never {
  throw new ParseError(
    node,
    "script_reserved_attribute",
    `The \`${name}\` attribute is reserved and cannot be used`,
  );
}

export function style_duplicate(node: NodeLike): never {
  throw new ParseError(
    node,
    "style_duplicate",
    "A component can have a single top-level `<style>` element",
  );
}

export function svelte_component_invalid_this(node: NodeLike): never {
  throw new ParseError(
    node,
    "svelte_component_invalid_this",
    "Invalid component definition — must be an `{expression}`",
  );
}

export function svelte_component_missing_this(node: NodeLike): never {
  throw new ParseError(
    node,
    "svelte_component_missing_this",
    "`<svelte:component>` must have a 'this' attribute",
  );
}

export function svelte_element_missing_this(node: NodeLike): never {
  throw new ParseError(
    node,
    "svelte_element_missing_this",
    "`<svelte:element>` must have a 'this' attribute with a value",
  );
}

export function svelte_meta_duplicate(node: NodeLike, name: string): never {
  throw new ParseError(
    node,
    "svelte_meta_duplicate",
    `A component can only have one \`<${name}>\` element`,
  );
}

export function svelte_meta_invalid_content(
  node: NodeLike,
  name: string,
): never {
  throw new ParseError(
    node,
    "svelte_meta_invalid_content",
    `<${name}> cannot have children`,
  );
}

export function svelte_meta_invalid_placement(
  node: NodeLike,
  name: string,
): never {
  throw new ParseError(
    node,
    "svelte_meta_invalid_placement",
    `\`<${name}>\` tags cannot be inside elements or blocks`,
  );
}

export function svelte_meta_invalid_tag(node: NodeLike, list: string): never {
  throw new ParseError(
    node,
    "svelte_meta_invalid_tag",
    `Valid \`<svelte:...>\` tag names are ${list}`,
  );
}

export function svelte_options_deprecated_tag(node: NodeLike): never {
  throw new ParseError(
    node,
    "svelte_options_deprecated_tag",
    '"tag" option is deprecated — use "customElement" instead',
  );
}

export function svelte_options_invalid_attribute(node: NodeLike): never {
  throw new ParseError(
    node,
    "svelte_options_invalid_attribute",
    "`<svelte:options>` can only receive static attributes",
  );
}

export function svelte_options_invalid_attribute_value(
  node: NodeLike,
  list: string,
): never {
  throw new ParseError(
    node,
    "svelte_options_invalid_attribute_value",
    `Value must be ${list}, if specified`,
  );
}

export function svelte_options_invalid_customelement(node: NodeLike): never {
  throw new ParseError(
    node,
    "svelte_options_invalid_customelement",
    '"customElement" must be a string literal defining a valid custom element name or an object of the form { tag?: string; shadow?: "open" | "none" | `ShadowRootInit`; props?: { [key: string]: { attribute?: string; reflect?: boolean; type: .. } } }',
  );
}

export function svelte_options_invalid_customelement_props(
  node: NodeLike,
): never {
  throw new ParseError(
    node,
    "svelte_options_invalid_customelement_props",
    '"props" must be a statically analyzable object literal of the form "{ [key: string]: { attribute?: string; reflect?: boolean; type?: "String" | "Boolean" | "Number" | "Array" | "Object" }"',
  );
}

export function svelte_options_invalid_customelement_shadow(
  node: NodeLike,
): never {
  throw new ParseError(
    node,
    "svelte_options_invalid_customelement_shadow",
    '"shadow" must be either "open", "none" or `ShadowRootInit` object.',
  );
}

export function svelte_options_invalid_tagname(node: NodeLike): never {
  throw new ParseError(
    node,
    "svelte_options_invalid_tagname",
    "Tag name must be lowercase and hyphenated",
  );
}

export function svelte_options_reserved_tagname(node: NodeLike): never {
  throw new ParseError(
    node,
    "svelte_options_reserved_tagname",
    "Tag name is reserved",
  );
}

export function svelte_options_unknown_attribute(
  node: NodeLike,
  name: string,
): never {
  throw new ParseError(
    node,
    "svelte_options_unknown_attribute",
    `\`<svelte:options>\` unknown attribute '${name}'`,
  );
}

export function tag_invalid_name(node: NodeLike): never {
  throw new ParseError(
    node,
    "tag_invalid_name",
    "Expected a valid element or component name. Components must have a valid variable name or dot notation expression",
  );
}

export function tag_invalid_placement(
  node: NodeLike,
  name: string,
  location: string,
): never {
  throw new ParseError(
    node,
    "tag_invalid_placement",
    `{@${name} ...} tag cannot be ${location}`,
  );
}

export function unexpected_eof(node: NodeLike): never {
  throw new ParseError(node, "unexpected_eof", "Unexpected end of input");
}

export function unexpected_reserved_word(node: NodeLike, word: string): never {
  throw new ParseError(
    node,
    "unexpected_reserved_word",
    `'${word}' is a reserved word in JavaScript and cannot be used here`,
  );
}

export function unterminated_string_constant(node: NodeLike): never {
  throw new ParseError(
    node,
    "unterminated_string_constant",
    "Unterminated string constant",
  );
}

export function void_element_invalid_content(node: NodeLike): never {
  throw new ParseError(
    node,
    "void_element_invalid_content",
    "Void elements cannot have children or closing tags",
  );
}
